### PR TITLE
Use official Homebrew Cask tap

### PR DESCRIPTION
**Pull request by vladimyr**
DevDocs has been added to Homebrew Cask: https://github.com/Homebrew/homebrew-cask/pull/86103
This PR updates readme to use official tap :tada:

### CODE REVIEW

**Comment by dteoh** [comment]
I feel conflicted about this... as the project owner, a conversation should have happened before it was submitted into Homebrew's default cask. If I wanted it in the default cask, I would have done it myself a long time ago. This project is maintained in my spare time, as such, I made decisions that allows me to minimize time spent on some tasks. The release procedure from start to finish takes me less than 10 minutes (push tag, write changelog, upload binary, update cask def) for full completion. Now the last bit is out of my control and will happen at some random time...

So who is going to maintain the default cask? What happens to all the existing users who installed from my cask?

I appreciate the effort you put into this... I just wish it started with a conversation...

**Comment by vladimyr** [comment]
Let me start by stating that I understand where are you coming from and hopefully my answer will clear some things out and make you feel better about this. 😉 

I don't have an official role in Homebrew (Cask) community but after contributing (and reviewing) fair share of casks and formulas I consider myself as someone who knows a thing or two about it.

> as the project owner, a conversation should have happened before it was submitted into Homebrew's default cask. If I wanted it in the default cask, I would have done it myself a long time ago.

This is not a typical flow. HBC is curated by end-users, and most of time they don't go and ask authors for approval. People can have different opinions about that one but that is the way things are right now. That doesn't mean you can't put a veto on your work being distributed through HBC, quite contrary:

> + The author has [specifically asked us not to include it](https://github.com/Homebrew/homebrew-cask/pull/5342).

from https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

Also, FWIW you couldn't really do it yourself a long time ago because that would be the case of self-submitting with presumably low star count and would probably end up rejected due to:

> + The Cask is for an app that is too obscure. Examples:
>   + A self-submitted app from a GitHub repository that is [not notable enough](https://github.com/Homebrew/homebrew-cask/pull/28103) (under 30 forks, 30 watchers, and 75 stars).

also from the https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/rejected_casks.md

To conclude, in most cases app gets submitted by (satisfied 😄 ) end-user after it gains certain popularity, and the author has the ability to put a veto if they find it undesirable.

> This project is maintained in my spare time, as such, I made decisions that allows me to minimize time spent on some tasks. The release procedure from start to finish takes me less than 10 minutes (push tag, write changelog, upload binary, update cask def) for full completion. Now the last bit is out of my control and will happen at some random time...

In the context of your scarce time resources, addition to HBC is literally the best thing that could happen. It simply makes you stop worrying about that last bit so the whole process goes even under 10 minutes. You say random time, but that is just a wrong impression. There is a whole automated system running behind the scenes described here https://github.com/Homebrew/homebrew-cask/issues/55268 and bunch of volunteers work daily to convert its output to actionable PRs (e.g. today's action report https://github.com/Homebrew/homebrew-cask/issues/55268#issuecomment-660536049). Now you could say, fine but opening update PR is one thing, and seeing it merged is another but there is a merge bot that detects updates and auto-merges them as soon as they land and get the green light from CI. This whole system relies on:
1. wonderful automated checker made by MacUpdater folks
2. appcasts (which is automatically generated by Github in your case)
3. awesome volunteers hourly/daily updating stuff
4. Github bots that detect and auto-merge updates

I hope you now have a clear picture of what is happening behind the scenes. If that helps here is a quite recent example of new webtorrent-desktop release:
1. author releases critical security fix https://github.com/webtorrent/webtorrent-desktop/releases/tag/v0.23.0
2. distribution gets updated https://github.com/Homebrew/homebrew-cask/pull/86083

I would argue this is a pretty fast response, what do you think? 😉 

> So who is going to maintain the default cask? What happens to all the existing users who installed from my cask?

I already answered that question but let me write it once again, a bunch of great! people (helped with automated tools) volunteering their time to keep HBC up to date and you are OFC free and more than welcome to join 😉 
The second question is trickier to answer... The short answer is you should let them know that they should migrate to the official tap. TBH I never did that and I'm not 100% sure how to advertise it properly so I can't give you a detailed answer but I'm sure you could get one on HB's discourse.

> I appreciate the effort you put into this... I just wish it started with a conversation...

Let me just close this by stating that all my actions were motivated by the goodwill and the best interests of both users and you as an author of this useful app. I apologize if the end result does not reflect that or somehow contradicts your vision. Feel free to ask me to remove it at any time if you decide so. Hopefully, you'll find it good move at the end 🤞

**Comment by dteoh** [comment]
Thank you for taking the time to explain. I'm satisfied by what you are telling me, so I think this will be a good move. 👍

**Comment by vladimyr** [comment]
It is my pleasure, I'm always up for the constructive discussions. Thank you for taking the time to go through all that and best of luck with DevDocs and all other future endeavors 😉

**Comment by ran-dall** [comment]
@vladimyr You're explanation of the "automated" system was slightly off, but still generally correct. The biggest thing is that the system, isn't really automated, it's an ML (Machine Learning) based system that runs on Hardware that is given to me by a few different parties including NVIDIA and Intel (generally people I have consulted for in the past). The 'MacUpdater folks' simply provided the learning material for the ML; but theoretically they are no longer required for the ML to push the updates daily. So theoretically it can work touch-free but I haven't had the time to fully automate it. We can go more into details at some later point, but just to get you a better idea of what's going on.

**Pull request merged**
